import fs from "fs";
import path from "path";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Home.module.css";
import { useState, useRef } from "react";

import ScatterChart from "/components/ScatterChart";

export async function getStaticPaths() {
  // const res = await fetch("http://localhost:3000/api/detail/all");
  // const data = await res.json();

  const source = path.join(process.cwd(), "/data/all.json");
  const data = JSON.parse(fs.readFileSync(source, "utf8"));

  return {
    paths: data,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const id = params.id;
  // const res1 = await fetch("http://localhost:3000/api/3dayhistory");
  // const historicalData = await res1.json();

  const historicalSource = path.join(process.cwd(), "/data/historical.json");
  const historicalData = JSON.parse(fs.readFileSync(historicalSource, "utf8"));

  // const res2 = await fetch(`http://localhost:3000/api/detail/${id}`);
  // const activeData = await res2.json();

  const activeData = {
    timestamp: "2020-12-18T03:00:00",
    precip_mm_max3hr: 0,
    risk: "low",
  };

  return {
    props: { historicalData, activeData },
  };
}

export default function Detail({ historicalData, activeData }) {
  console.log(activeData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{activeData.timestamp}</h1>
        <p>{activeData.risk}</p>
        {/*   <ScatterChart
          historicalData={historicalData}
          activeData={activeData}
          height={400}
          width={500}
        />*/}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
