import fs from "fs";
import path from "path";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Home.module.css";
import { useState, useEffect } from "react";
import { ResponsiveScatterPlotCanvas } from "@nivo/scatterplot";

import historicalData from "/data/historical.json";

export async function getStaticPaths() {
  // const res = await fetch("http://localhost:3008/api/detail/all");
  // const data = await res.json();

  const source = path.join(process.cwd(), "/data/all.json");
  const data = JSON.parse(fs.readFileSync(source, "utf8"));

  return {
    paths: data,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const id = params.id;
<<<<<<< HEAD
  // const res1 = await fetch("http://localhost:3008/api/3dayhistory");
  // const historicalData = await res1.json();

  const historicalSource = path.join(process.cwd(), "/data/historical.json");
  const historicalData = JSON.parse(fs.readFileSync(historicalSource, "utf8"));

  // const res2 = await fetch(`http://localhost:3008/api/detail/${id}`);
=======
  // const res2 = await fetch(`http://localhost:3000/api/detail/${id}`);
>>>>>>> fda3315 (Use nivo for detail chart)
  // const activeData = await res2.json();

  const activeData = {
    timestamp: "2020-12-14T9:00:00",
    precip_mm_max3hr: 0,
  };

  return {
    props: { activeData },
  };
}

export default function Detail({ activeData }) {
  const historical = historicalData.map((d) => {
    return {
      x: d.day,
      y: d.precip_mm_max3hr,
      event: d.event,
    };
  });
  const data = [
    {
      id: "nolandslide",
      data: historical,
    },
    {
      id: "landslide",
      data: historical.filter((d) => d.event === 1),
    },
    {
      id: "active",
      data: [
        {
          x: activeData.timestamp.split("T")[0],
          y: activeData.precip_mm_max3hr,
          event: 2,
        },
      ],
    },
  ];

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.chart}>
          {mounted && (
            <ResponsiveScatterPlotCanvas
              isInteractive={false}
              useMesh={false}
              debugMesh={false}
              data={data}
              colors={["rgba(0, 0, 0, 0.2)", "red", "green"]}
              margin={{ top: 60, right: 5, bottom: 70, left: 60 }}
              nodeSize={(d) =>
                d.serieId === "nolandslide"
                  ? 5
                  : d.serieId === "landslide"
                  ? 7
                  : 10
              }
              xScale={{ type: "time", format: "%Y-%m-%d", precision: "day" }}
              xFormat=">-.2f"
              yScale={{ type: "linear", min: 0, max: "auto" }}
              yFormat=">-.2f"
              axisTop={null}
              axisRight={null}
              axisBottom={{
                orient: "bottom",
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                format: "%Y",
                tickValues: "every 4 years",
                legendPosition: "middle",
                legendOffset: 0,
              }}
              axisLeft={{
                orient: "left",
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legend: "3 hour rainfall (mm)",
                legendPosition: "middle",
                legendOffset: -50,
              }}
              theme={{
                background: "#fff",
                textColor: "#333333",
                fontSize: 16,
                axis: {
                  domain: {
                    line: {
                      stroke: "#777777",
                      strokeWidth: 1,
                    },
                  },
                  legend: {
                    text: {
                      fontSize: 16,
                      fontWeight: 600,
                      fill: "#333333",
                    },
                  },
                  ticks: {
                    line: {
                      strokeWidth: 0,
                    },
                    text: {
                      fontSize: 16,
                      fill: "#333333",
                    },
                  },
                },
                grid: {
                  line: {
                    stroke: "#dddddd",
                    strokeWidth: 1,
                  },
                },
                annotations: {
                  text: {
                    fontSize: 16,
                    fill: "#333333",
                    outlineWidth: 2,
                    outlineColor: "#ffffff",
                    outlineOpacity: 1,
                  },
                  link: {
                    stroke: "#000000",
                    strokeWidth: 1,
                    outlineWidth: 2,
                    outlineColor: "#ffffff",
                    outlineOpacity: 1,
                  },
                  outline: {
                    stroke: "#000000",
                    strokeWidth: 2,
                    outlineWidth: 2,
                    outlineColor: "#ffffff",
                    outlineOpacity: 1,
                  },
                  symbol: {
                    fill: "#000000",
                    outlineWidth: 2,
                    outlineColor: "#ffffff",
                    outlineOpacity: 1,
                  },
                },
              }}
            />
          )}
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
