import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Home.module.css";
import { useState, useEffect, useRef } from "react";

import ScatterChart from "/components/ScatterChart";

export async function getStaticPaths() {
  const res = await fetch("http://localhost:3000/api/detail/all");
  const data = await res.json();

  return {
    paths: data,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const id = params.id;
  const res1 = await fetch("http://localhost:3000/api/3dayhistory");
  const historicalData = await res1.json();

  const res2 = await fetch(`http://localhost:3000/api/detail/${id}`);
  const activeData = await res2.json();

  return {
    props: { historicalData, activeData },
  };
}

export default function Detail({ historicalData, activeData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ScatterChart
          historicalData={historicalData}
          activeData={activeData}
          height={400}
          width={500}
        />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
