import fs from "fs";
import path from "path";
import Head from "next/head";
import Link from "next/link";
import stylesDetail from "/styles/Detail.module.css";
import stylesArticle from "/styles/Article.module.css";
import { useState, useEffect } from "react";
import { ResponsiveScatterPlotCanvas } from "@nivo/scatterplot";

import Risk from "../../components/Risk";
import DetailContent from "../../content/DetailContent.mdx";
import historicalData from "/data/historical.json";
import riskDefinitions from "/content/riskDefinitions";
import Page from "/components/Page";

const styles = { ...stylesDetail, ...stylesArticle };

export async function getStaticPaths() {
  // const res = await fetch("http://localhost:3008/api/detail/all");
  // const data = await res.json();

  const source = path.join(process.cwd(), "/data/index.json");
  const data = JSON.parse(fs.readFileSync(source, "utf8"));

  return {
    paths: data.threeday.hours.map((hour) => {
      return {
        params: hour,
      };
    }),
    fallback: "blocking",
  };
}

export async function getStaticProps({ params }) {
  const historicalSource = path.join(process.cwd(), "/data/historical.json");
  const historicalData = JSON.parse(fs.readFileSync(historicalSource, "utf8"));

  // const res2 = await fetch(`http://localhost:3000/api/detail/${id}`);
  // const activeData = await res2.json();

  const activeData = {
    timestamp: "2020-12-14T9:00:00",
    precip_mm_max3hr: 0.14,
    riskNumber: 0,
    riskLevel: 0,
    datetime: "April 5 · 3PM–6PM",
  };

  return {
    props: { activeData },
  };
}

export default function Detail({ activeData }) {
  const historical = historicalData.map((d) => {
    return {
      x: d.day,
      y: d.precip_mm_max3hr,
      event: d.event,
    };
  });
  const data = [
    {
      id: "nolandslide",
      data: historical,
    },
    {
      id: "landslide",
      data: historical.filter((d) => d.event === 1),
    },
    {
      id: "active",
      data: [
        {
          x: activeData.timestamp.split("T")[0],
          y: activeData.precip_mm_max3hr,
          event: 2,
        },
      ],
    },
  ];

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  let theme = {
    background: "transparent",
    textColor: "#333333",
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
    axis: {
      domain: {
        line: {
          stroke: "#777777",
          strokeWidth: 1,
        },
      },
      legend: {
        text: {
          fontSize: 14,
          fontWeight: 600,
          fill: "#333333",
        },
      },
      ticks: {
        line: {
          strokeWidth: 0,
        },
        text: {
          fontSize: 14,
          fill: "#333333",
        },
      },
    },
    grid: {
      line: {
        stroke: "#454545",
        strokeWidth: 1,
      },
    },
    annotations: {
      text: {
        fontSize: 14,
        fill: "#333333",
        outlineWidth: 2,
        outlineColor: "#ffffff",
        outlineOpacity: 1,
      },
    },
  };

  if (
    typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-color-scheme: dark)").matches
  ) {
    theme = {
      background: "transparent",
      textColor: "#cfcfd8",
      fontSize: 14,
      fontFamily:
        "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
      axis: {
        domain: {
          line: {
            stroke: "#454545",
            strokeWidth: 1,
          },
        },
        legend: {
          text: {
            fontSize: 14,
            fontWeight: 600,
            fill: "#cfcfd8",
          },
        },
        ticks: {
          line: {
            strokeWidth: 0,
          },
          text: {
            fontSize: 14,
            fill: "#cfcfd8",
          },
        },
      },
      grid: {
        line: {
          stroke: "#454545",
          strokeWidth: 1,
        },
      },
      annotations: {
        text: {
          fontSize: 14,
          fill: "#cfcfd8",
          outlineWidth: 2,
          outlineColor: "#ffffff",
          outlineOpacity: 1,
        },
      },
    };
  }

  return (
    <Page title="Risk detail" description={activeData.datetime}>
      <div>
        <Head>
          <title>{activeData.datetime} | Sitka Landslide Risk</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className={styles.figures}>
            <div className={styles.risk}>
              <h3 className={styles.figureHeading}>Risk</h3>
              <div className={styles.riskBar}>
                <div
                  style={{ left: `${activeData.riskNumber * 100}%` }}
                  className={styles.riskBarIcon}
                >
                  <Risk riskLevel={activeData.riskLevel} hasText={false} />
                </div>
                <div className={styles.riskBarLine}></div>
                <div className={styles.riskBarLegend}>
                  <div>{riskDefinitions[0].abbreviated}</div>
                  <div>{riskDefinitions[1].abbreviated}</div>
                  <div>{riskDefinitions[2].abbreviated}</div>
                </div>
              </div>
            </div>
            <div className={styles.rainfall}>
              <h3 className={styles.figureHeading}>3 hour rainfall</h3>
              <div className={styles.rainfallNumber}>{activeData.precip_mm_max3hr}″</div>
            </div>
          </div>
          <hr />
          <div className={styles.chart}>
            {mounted && (
              <ResponsiveScatterPlotCanvas
                isInteractive={false}
                useMesh={false}
                debugMesh={false}
                data={data}
                colors={["rgba(0, 0, 0, 0.2)", "red", "green"]}
                margin={{ top: 10, right: 5, bottom: 30, left: 60 }}
                nodeSize={(d) =>
                  d.serieId === "nolandslide" ? 5 : d.serieId === "landslide" ? 7 : 10
                }
                xScale={{ type: "time", format: "%Y-%m-%d", precision: "day" }}
                xFormat=">-.2f"
                yScale={{ type: "linear", min: 0, max: "auto" }}
                yFormat=">-.2f"
                axisTop={null}
                axisRight={null}
                axisBottom={{
                  orient: "bottom",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  format: "%Y",
                  tickValues: "every 4 years",
                  legendPosition: "middle",
                  legendOffset: 0,
                }}
                axisLeft={{
                  orient: "left",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  legend: "3 hour rainfall (in.)",
                  legendPosition: "middle",
                  legendOffset: -50,
                }}
                theme={theme}
              />
            )}
          </div>
          <DetailContent />
        </>
      </div>
    </Page>
  );
}
