import Head from "next/head";
import stylesDetail from "/styles/Detail.module.css";
import stylesArticle from "/styles/Article.module.css";
import { useState, useEffect } from "react";
import { ResponsiveScatterPlotCanvas } from "@nivo/scatterplot";

import Risk from "../../components/Risk";
import DetailContent from "../../content/DetailContent.mdx";
import riskDefinitions from "/content/riskDefinitions";
import Page from "/components/Page";

import historicalDataMM from "/data/historical.json";
import rainfallData from "/data/rainfall.json";

const styles = { ...stylesDetail, ...stylesArticle };

// Convert historical rainfall to inches
const historicalData = historicalDataMM.map(({ day, precip_mm_max3hr, event }) => ({
  day,
  riskPrecipInches: precip_mm_max3hr / 25.4,
  event,
}));

const maxRiskPrecipInches = Math.max(...historicalData.map((d) => d.riskPrecipInches));

export async function getStaticPaths() {
  return {
    paths: [{ params: { timestamp: "current" } }].concat(
      rainfallData.threeDays.hours.map((hour) => {
        return {
          // Note: the path param is called 'timestamp' but we're using the data field that has a
          // shortened version (so the URLs won't be needlessly cluttered).
          params: { timestamp: hour.shortTimestamp },
        };
      })
    ),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const activeData =
    params.timestamp === "current"
      ? rainfallData.current
      : rainfallData.threeDays.hours.find((h) => params.timestamp === h.shortTimestamp);

  return {
    props: { activeData },
  };
}

export default function Detail({ activeData }) {
  const historical = historicalData.map((d) => {
    return {
      x: d.day,
      y: d.riskPrecipInches,
      event: d.event,
    };
  });

  const lastHistoricalDate = historical[historical.length - 1].x;

  const chartData = [
    {
      id: "nolandslide",
      data: historical.filter((d) => d.event === 0),
    },
    {
      id: "landslide",
      data: historical.filter((d) => d.event === 1),
    },
    {
      id: "active",
      data: [
        {
          x: lastHistoricalDate,
          y: activeData.riskPrecipInches,
          event: 2,
        },
      ],
    },
  ];

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  const prefersDarkTheme =
    typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-color-scheme: dark)").matches;

  let theme = prefersDarkTheme
    ? {
        background: "transparent",
        textColor: "#cfcfd8",
        fontSize: 14,
        fontFamily:
          "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
        axis: {
          domain: {
            line: {
              stroke: "#454545",
              strokeWidth: 1,
            },
          },
          legend: {
            text: {
              fontSize: 14,
              fontWeight: 600,
              fill: "#cfcfd8",
            },
          },
          ticks: {
            line: {
              strokeWidth: 0,
            },
            text: {
              fontSize: 14,
              fill: "#cfcfd8",
            },
          },
        },
        grid: {
          line: {
            stroke: "#454545",
            strokeWidth: 1,
          },
        },
        annotations: {
          text: {
            fontSize: 14,
            fill: "#cfcfd8",
            outlineWidth: 2,
            outlineColor: "#ffffff",
            outlineOpacity: 1,
          },
        },
      }
    : {
        background: "transparent",
        textColor: "#333333",
        fontSize: 14,
        fontFamily:
          "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
        axis: {
          domain: {
            line: {
              stroke: "#999",
              strokeWidth: 1,
            },
          },
          legend: {
            text: {
              fontSize: 14,
              fontWeight: 600,
              fill: "#333333",
            },
          },
          ticks: {
            line: {
              strokeWidth: 0,
            },
            text: {
              fontSize: 14,
              fill: "#333333",
            },
          },
        },
        grid: {
          line: {
            stroke: "#eee",
            strokeWidth: 1,
          },
        },
        annotations: {
          text: {
            fontSize: 14,
            fill: "#333333",
            outlineWidth: 2,
            outlineColor: "#ffffff",
            outlineOpacity: 1,
          },
        },
      };

  return (
    <Page title="Risk detail" description={activeData.datetimeLabel}>
      <div>
        <Head>
          <title>{activeData.datetimeLabel} | Sitka Landslide Risk</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className={styles.figures}>
            <div className={styles.risk}>
              <h3 className={styles.figureHeading}>Risk</h3>
              <div className={styles.riskBar}>
                <div
                  style={{ left: `${activeData.riskProb * 100}%` }}
                  className={styles.riskBarIcon}
                >
                  <Risk riskLevel={activeData.riskLevel} hasText={false} />
                </div>
                <div className={styles.riskBarLine}></div>
                <div className={styles.riskBarLegend}>
                  <div>{riskDefinitions[0].abbreviated}</div>
                  <div>{riskDefinitions[1].abbreviated}</div>
                  <div>{riskDefinitions[2].abbreviated}</div>
                </div>
              </div>
            </div>
            <div className={styles.rainfall}>
              <h3 className={styles.figureHeading}>3 hour rainfall</h3>
              <div className={styles.rainfallNumber}>{activeData.riskPrecipInches}″</div>
            </div>
          </div>
          <hr />
          <div className={styles.chart}>
            <div
              className={`${styles.forecast} ${activeData.riskPrecipInches > 1 && styles.arrowUp}`}
              // Position the annotation arrow; set a fixed position for when the current value is
              // higher than all of the historical data
              style={{
                bottom:
                  activeData.riskPrecipInches > maxRiskPrecipInches
                    ? "90%"
                    : (activeData.riskPrecipInches / 1.6) * 85 + "%",
              }}
            >
              <span className={styles.forecastText}>{activeData.datetimeLabel}</span>
              <svg
                width="41"
                height="35"
                viewBox="0 0 41 35"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className={styles.forecastArrow}
              >
                <path
                  d="M35.5 35L40.0637 24.3931L28.5961 25.7442L35.5 35ZM-4.30478e-08 2C15.0421 2 29.5769 10.5585 33.4764 26.3033L35.4177 25.8225C31.2472 8.98325 15.7355 6.77377e-07 4.30478e-08 0L-4.30478e-08 2Z"
                  fill="black"
                />
              </svg>
            </div>
            {mounted && (
              <ResponsiveScatterPlotCanvas
                isInteractive={false}
                useMesh={false}
                debugMesh={false}
                data={chartData}
                colors={["rgba(0, 0, 0, 0.2)", "#FFBC57", "#30B0C9"]}
                margin={{ top: 10, right: 5, bottom: 30, left: 60 }}
                nodeSize={(d) =>
                  d.serieId === "nolandslide" ? 2 : d.serieId === "landslide" ? 8 : 8
                }
                xScale={{ type: "time", format: "%Y-%m-%d", precision: "day" }}
                xFormat=">-.2f"
                yScale={{ type: "linear", min: 0, max: "auto" }}
                yFormat=">-.2f"
                axisTop={null}
                axisRight={null}
                axisBottom={{
                  orient: "bottom",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  format: "%Y",
                  tickValues: "every 6 years",
                  legendPosition: "middle",
                  legendOffset: 0,
                }}
                axisLeft={{
                  orient: "left",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  legend: "3 hour rainfall (in.)",
                  legendPosition: "middle",
                  legendOffset: -50,
                }}
                theme={theme}
              />
            )}
          </div>
          <DetailContent />
        </>
      </div>
    </Page>
  );
}
