import Head from "next/head";
import stylesDetail from "/styles/Detail.module.css";
import stylesArticle from "/styles/Article.module.css";
import { useState, useEffect } from "react";
import { ResponsiveScatterPlotCanvas } from "@nivo/scatterplot";

import Risk from "../../components/Risk";
import DetailContent from "../../content/DetailContent.mdx";
import riskDefinitions from "/content/riskDefinitions";
import Page from "/components/Page";

import historicalDataMM from "/data/historical.json";
import rainfallData from "/data/rainfall.json";

const styles = { ...stylesDetail, ...stylesArticle };

// Convert historical rainfall to inches
const historicalData = historicalDataMM.map(({ day, precip_mm_max3hr, event }) => ({
  day,
  riskPrecipInches: precip_mm_max3hr / 25.4,
  event,
}));

export async function getStaticPaths() {
  return {
    paths: [{ params: { timestamp: "current" } }].concat(
      rainfallData.threeDays.hours.map((hour) => {
        return {
          params: { timestamp: hour.timestamp.split(".")[0] },
        };
      })
    ),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const activeData =
    params.timestamp === "current"
      ? rainfallData.current
      : rainfallData.threeDays.hours.find((h) => params.timestamp === h.timestamp.split(".")[0]);

  return {
    props: { activeData },
  };
}

export default function Detail({ activeData }) {
  const historical = historicalData.map((d) => {
    return {
      x: d.day,
      y: d.riskPrecipInches,
      event: d.event,
    };
  });
  const chartData = [
    {
      id: "nolandslide",
      data: historical.filter((d) => d.event === 0),
    },
    {
      id: "landslide",
      data: historical.filter((d) => d.event === 1),
    },
    {
      id: "active",
      data: [
        {
          x: activeData.timestamp.split("T")[0],
          y: activeData.riskPrecipInches,
          event: 2,
        },
      ],
    },
  ];

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  let theme = {
    background: "transparent",
    textColor: "#333333",
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
    axis: {
      domain: {
        line: {
          stroke: "#777777",
          strokeWidth: 1,
        },
      },
      legend: {
        text: {
          fontSize: 14,
          fontWeight: 600,
          fill: "#333333",
        },
      },
      ticks: {
        line: {
          strokeWidth: 0,
        },
        text: {
          fontSize: 14,
          fill: "#333333",
        },
      },
    },
    grid: {
      line: {
        stroke: "#454545",
        strokeWidth: 1,
      },
    },
    annotations: {
      text: {
        fontSize: 14,
        fill: "#333333",
        outlineWidth: 2,
        outlineColor: "#ffffff",
        outlineOpacity: 1,
      },
    },
  };

  if (
    typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-color-scheme: dark)").matches
  ) {
    theme = {
      background: "transparent",
      textColor: "#cfcfd8",
      fontSize: 14,
      fontFamily:
        "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
      axis: {
        domain: {
          line: {
            stroke: "#454545",
            strokeWidth: 1,
          },
        },
        legend: {
          text: {
            fontSize: 14,
            fontWeight: 600,
            fill: "#cfcfd8",
          },
        },
        ticks: {
          line: {
            strokeWidth: 0,
          },
          text: {
            fontSize: 14,
            fill: "#cfcfd8",
          },
        },
      },
      grid: {
        line: {
          stroke: "#454545",
          strokeWidth: 1,
        },
      },
      annotations: {
        text: {
          fontSize: 14,
          fill: "#cfcfd8",
          outlineWidth: 2,
          outlineColor: "#ffffff",
          outlineOpacity: 1,
        },
      },
    };
  }

  return (
    <Page title="Risk detail" description={activeData.datetimeLabel}>
      <div>
        <Head>
          <title>{activeData.datetimeLabel} | Sitka Landslide Risk</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className={styles.figures}>
            <div className={styles.risk}>
              <h3 className={styles.figureHeading}>Risk</h3>
              <div className={styles.riskBar}>
                <div
                  style={{ left: `${activeData.riskProb * 100}%` }}
                  className={styles.riskBarIcon}
                >
                  <Risk riskLevel={activeData.riskLevel} hasText={false} />
                </div>
                <div className={styles.riskBarLine}></div>
                <div className={styles.riskBarLegend}>
                  <div>{riskDefinitions[0].abbreviated}</div>
                  <div>{riskDefinitions[1].abbreviated}</div>
                  <div>{riskDefinitions[2].abbreviated}</div>
                </div>
              </div>
            </div>
            <div className={styles.rainfall}>
              <h3 className={styles.figureHeading}>3 hour rainfall</h3>
              <div className={styles.rainfallNumber}>{activeData.riskPrecipInches}″</div>
            </div>
          </div>
          <hr />
          <div className={styles.chart}>
            {mounted && (
              <ResponsiveScatterPlotCanvas
                isInteractive={false}
                useMesh={false}
                debugMesh={false}
                data={chartData}
                colors={["rgba(0, 0, 0, 0.2)", "red", "green"]}
                margin={{ top: 10, right: 5, bottom: 30, left: 60 }}
                nodeSize={(d) =>
                  d.serieId === "nolandslide" ? 5 : d.serieId === "landslide" ? 7 : 10
                }
                xScale={{ type: "time", format: "%Y-%m-%d", precision: "day" }}
                xFormat=">-.2f"
                yScale={{ type: "linear", min: 0, max: "auto" }}
                yFormat=">-.2f"
                axisTop={null}
                axisRight={null}
                axisBottom={{
                  orient: "bottom",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  format: "%Y",
                  tickValues: "every 4 years",
                  legendPosition: "middle",
                  legendOffset: 0,
                }}
                axisLeft={{
                  orient: "left",
                  tickSize: 5,
                  tickPadding: 5,
                  tickRotation: 0,
                  legend: "3 hour rainfall (in.)",
                  legendPosition: "middle",
                  legendOffset: -50,
                }}
                theme={theme}
              />
            )}
          </div>
          <DetailContent />
        </>
      </div>
    </Page>
  );
}
