import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import { scaleLinear, scaleTime, area, line, curveLinear } from "d3";

import { useState, useEffect, useRef } from "react";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/today");
  const data = await res.json();

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  const margin = { top: 30, right: 0, bottom: 30, left: 40 };
  const width = 400;
  const height = 160;

  const minY = 0;
  const maxY = 1;

  const scaleY = scaleLinear()
    .domain([maxY, minY])
    .range([margin.top, height - margin.bottom]);

  const labelsY = [
    { position: 1 / 6, text: "Low" },
    { position: 3 / 6, text: "Med" },
    { position: 5 / 6, text: "High" },
  ];

  const ticksY = [0, 0.333, 0.666, 1];

  const numberOfTimes = 7;

  const scaleX = scaleTime()
    .domain([0, numberOfTimes])
    .range([margin.left, width - margin.right]);

  const ticksX = data.hour24;

  const createArea = area()
    .x((d) => scaleX(d.id))
    .y0(scaleY(0))
    .y1((d) => scaleY(d.risk))
    .curve(curveLinear);

  const createLine = line()
    .x((d) => scaleX(d.id))
    .y((d) => scaleY(d.risk))
    .curve(curveLinear);

  const lineSegments = [];

  for (let i = 0; i < numberOfTimes; i++) {
    lineSegments.push(createLine(data.hour24.slice(i, i + 2)));
  }

  const areaSegments = [];

  for (let i = 0; i < numberOfTimes; i++) {
    areaSegments.push(createArea(data.hour24.slice(i, i + 2)));
  }

  function getRiskColor(riskLevel) {
    switch (riskLevel) {
      case "low":
        return "#068677";
        break;
      case "medium":
        return "#ECCA51";
        break;
      case "high":
        return "#D3354F";
        break;
      default:
        return "#666";
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href="/detail/0001">
              <a>Detail 0001</a>
            </Link>
          </li>
          <li>
            <Link href="/detail/0002">
              <a>Detail 0002</a>
            </Link>
          </li>
          <li>
            <Link href="/detail/0003">
              <a>Detail 0003</a>
            </Link>
          </li>
          <li>
            <Link href="/map">
              <a>Map view</a>
            </Link>
          </li>
        </ul>
        <div id="chart">
          <svg width={width} height={height} viewBox={`0 0 ${width} ${height}`}>
            {ticksY.map((tick, i) => {
              return (
                <g
                  key={i}
                  className="tick"
                  transform={`translate(${margin.left},${0})`}
                >
                  <line
                    className="line-y"
                    x2={width - margin.right - margin.left}
                    y1={Math.floor(scaleY(tick))}
                    y2={Math.floor(scaleY(tick))}
                  />
                </g>
              );
            })}
            {labelsY.map((label, i) => {
              return (
                <g
                  key={i}
                  className="tick"
                  transform={`translate(${margin.left},${0})`}
                >
                  <text
                    dy="0.2em"
                    className="tick-y"
                    x={-30}
                    y={scaleY(label.position)}
                  >
                    {label.text}
                  </text>
                </g>
              );
            })}
            <g>
              {lineSegments.map((segment, i) => (
                <path
                  key={i}
                  className="chart-line"
                  stroke={getRiskColor(data.hour24[i].riskLevel)}
                  strokeWidth="3"
                  fill="transparent"
                  d={segment}
                ></path>
              ))}
            </g>
            <g>
              {areaSegments.map((segment, i) => (
                <path
                  key={i}
                  className="chart-area"
                  fill={getRiskColor(data.hour24[i].riskLevel)}
                  d={segment}
                ></path>
              ))}
            </g>
            {ticksX.map((tick, i) => {
              return (
                <g key={i} className="tick">
                  <text
                    dy="2"
                    className="tick-x"
                    x={scaleX(i)}
                    y={height - margin.bottom + 20}
                  >
                    {tick.time}
                  </text>
                </g>
              );
            })}
          </svg>
        </div>
      </main>
      {/*<footer className={styles.footer}></footer>*/}
      <style>{`
          html {
            font-family: graphik;
          }

          line {
            shape-rendering: crispEdges
          }

          .chart-area {
            fill-opacity: 0.5;
            shape-rendering: crispEdges;
          }

          .tick-x {
            text-anchor: start;
          }

          text {
            font-family: graphik;
            font-size: 12px;
          }

          .line-y {
            stroke: rgb(0 0 0 / 20%);
            stroke-width: 1
          }

          .chart-label {
            text-align: center;
            margin-top: -10px;
            font-weight: 500;
            font-size: 14px;
          }
          strong {
            font-weight: 500;
          }
         
      `}</style>
    </div>
  );
}
