import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import mapboxgl from "!mapbox-gl";
import { useState, useEffect } from "react";

export default function Home() {
  mapboxgl.accessToken =
    "pk.eyJ1IjoiYXphdmVhIiwiYSI6IkFmMFBYUUUifQ.eYn6znWt8NzYOa3OrWop8A";

  const [pageIsMounted, setPageIsMounted] = useState(false);

  useEffect(() => {
    setPageIsMounted(true);
    if (!pageIsMounted) {
      const map = new mapboxgl.Map({
        container: "map",
        style: "mapbox://styles/azavea/ckz3jjuxd001x15nr01wh9fve",
        center: [-135.32, 57.0531], // starting position [lng, lat]
        zoom: 10, // starting zoom
      });
      var nav = new mapboxgl.NavigationControl({
        showCompass: true,
        showZoom: true,
      });

      map.addControl(nav, "bottom-right");
    }
  }, []);

  return (
    <div className={styles.container}>
      <style>{`
        .map {
         height: 800px;
         width: 100%;
        }
      `}</style>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div id="map" className="map"></div>
      </main>

      {/*<footer className={styles.footer}></footer>*/}
    </div>
  );
}
