import Head from "next/head";
import Link from "next/link";
import mapboxgl from "!mapbox-gl";
import { useState, useEffect } from "react";

export default function Home() {
<<<<<<< HEAD
  mapboxgl.accessToken = "pk.eyJ1IjoiYXphdmVhIiwiYSI6IkFmMFBYUUUifQ.eYn6znWt8NzYOa3OrWop8A";
=======
  mapboxgl.accessToken =
<<<<<<< HEAD
    "pk.eyJ1IjoiYXphdmVhIiwiYSI6IkFmMFBYUUUifQ.eYn6znWt8NzYOa3OrWop8A";
>>>>>>> fda3315 (Use nivo for detail chart)
=======
    "pk.eyJ1IjoibGtuYXJmIiwiYSI6IjhjbGg4RUkifQ.-lS6mAkmR3SVh-W4XwQElg";
>>>>>>> e8dfc37 (Continuing frontend development)

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    if (!mounted) {
      const map = new mapboxgl.Map({
        container: "map",
        style: "mapbox://styles/lknarf/cl0pf3asg000114nt5jepzs6s",
        center: [-135.32, 57.0531],
        minZoom: 8,
        zoom: 10,
        maxZoom: 15,
        hash: true,
      });

      map.on("load", function () {
        map.addSource("raster-risk", {
          type: "raster",
          tiles: [
            window.location.origin +
              "/images/tiles/risk-purple/{z}/{x}/{y}.png",
          ],
          minzoom: 8,
          maxzoom: 15,
          tileSize: 512,
        });

        map.addLayer({
          id: "sky",
          type: "sky",
          paint: {
            "sky-type": "atmosphere",
            "sky-atmosphere-sun": [0.0, 0.0],
            "sky-atmosphere-sun-intensity": 15,
          },
        });

        map.setPaintProperty("satellite", "raster-saturation", -0.666);

        map.addLayer({
          id: "simple-tiles",
          type: "raster",
          source: "raster-risk",
          minzoom: 0,
          maxzoom: 20,
          paint: {
            "raster-resampling": "nearest",
            "raster-hue-rotate": 50,
            "raster-opacity": [
              "interpolate",
              ["exponential", 0.85],
              ["zoom"],
              12,
              0.75,
              18,
              0.65,
            ],
          },
        });
      });

      var nav = new mapboxgl.NavigationControl({
        showCompass: true,
        showZoom: true,
      });

      map.addControl(nav, "bottom-right");
    }
<<<<<<< HEAD
  }, [pageIsMounted]);
=======
  }, []);
>>>>>>> fda3315 (Use nivo for detail chart)

  return (
    <div>
      <style>{`
        .map {
         height: 800px;
         width: 100%;
        }
      `}</style>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
<<<<<<< HEAD
        <link href="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css" rel="stylesheet" />
=======
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css"
          rel="stylesheet"
        />
>>>>>>> fda3315 (Use nivo for detail chart)
      </Head>

      <main className="main">
        <div id="map" className="map"></div>
      </main>
<<<<<<< HEAD
<<<<<<< HEAD
=======

      {/*<footer className={styles.footer}></footer>*/}
>>>>>>> fda3315 (Use nivo for detail chart)
=======
>>>>>>> e8dfc37 (Continuing frontend development)
    </div>
  );
}
