import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import AreaChart from "/components/AreaChart";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/today");
  const data = await res.json();

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href="/detail/0001">
              <a>Detail 0001</a>
            </Link>
          </li>
          <li>
            <Link href="/detail/0002">
              <a>Detail 0002</a>
            </Link>
          </li>
          <li>
            <Link href="/detail/0003">
              <a>Detail 0003</a>
            </Link>
          </li>
          <li>
            <Link href="/map">
              <a>Map view</a>
            </Link>
          </li>
        </ul>
        <div id="chart">
          <AreaChart data={data.hour24} height={400} width={500} />
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
