#!/bin/bash

set -e

ENVIRONMENT="${ENVIRONMENT:-sitkaproduction}"

export TZ="America/Sitka"
TIMESTAMP=$(TZ="America/Sitka" date -Iminutes)
YEAR=$(date "+%Y")
MONTH=$(date "+%m")

echo "Building site."
yarn export

echo "Uploading to S3."
aws s3 sync --delete --only-show-errors out/ "s3://${ENVIRONMENT}/"

echo "Copying rainfall.json to archive."
aws s3 cp out/data/rainfall.json "s3://${ENVIRONMENT}-archive/rainfall/${YEAR}/${MONTH}/rainfall-${TIMESTAMP}.json"

echo "Finished"
