name: Build Pages Site

on:
  push:
    branches: [testthis]
  pull_request:
    branches: [develop]
  #schedule:
  #  - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"

    steps:
      - name: Build and export
        run: /usr/bin/ls -alh
