name: Build Pages Site

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    # Runs "at 9 past every 6 hours" (see https://crontab.guru)
    - cron: "9 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"

    steps:
      - uses: actions/checkout@v3
      - name: Build and export
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run next export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out
